/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface StudioForm {
        /**
          * Indicates loading state
         */
        "isLoading": boolean;
    }
    interface StudioLoader {
    }
}
declare global {
    interface HTMLStudioFormElement extends Components.StudioForm, HTMLStencilElement {
    }
    var HTMLStudioFormElement: {
        prototype: HTMLStudioFormElement;
        new (): HTMLStudioFormElement;
    };
    interface HTMLStudioLoaderElement extends Components.StudioLoader, HTMLStencilElement {
    }
    var HTMLStudioLoaderElement: {
        prototype: HTMLStudioLoaderElement;
        new (): HTMLStudioLoaderElement;
    };
    interface HTMLElementTagNameMap {
        "studio-form": HTMLStudioFormElement;
        "studio-loader": HTMLStudioLoaderElement;
    }
}
declare namespace LocalJSX {
    interface StudioForm {
        /**
          * Indicates loading state
         */
        "isLoading"?: boolean;
        "onFormSubmitted"?: (event: CustomEvent<any>) => void;
    }
    interface StudioLoader {
    }
    interface IntrinsicElements {
        "studio-form": StudioForm;
        "studio-loader": StudioLoader;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "studio-form": LocalJSX.StudioForm & JSXBase.HTMLAttributes<HTMLStudioFormElement>;
            "studio-loader": LocalJSX.StudioLoader & JSXBase.HTMLAttributes<HTMLStudioLoaderElement>;
        }
    }
}
